/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;
import model.DataService;
import model.Doctor;
import model.Encounter;
import model.Patient;
import model.VitalSigns;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
/**
 *
 * @author madhav
 */
public final class CreateEncounterJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateEncounterJPanel
     */
    
    String pid;
        String did;
       String vid;
    DataService ds;
    
    public CreateEncounterJPanel(DataService ds) {
        initComponents();
        this.ds=ds;
        //this.jcombobox.removeAllItems();
        //this.jcombobox.getSelectdItem();
                this.cbPatient.removeAllItems();
         for(Patient p:ds.getPatient())
        {
            
           this.cbPatient.addItem(p.getPatientName());
          
        }
         if(cbPatient.getSelectedItem()!=null){
         String selVal= cbPatient.getSelectedItem().toString();
          
          pid=getIdByNamePatient(selVal);
         }
         System.out.println(pid+"************");
         
        for(Doctor d:ds.getDoctr())
        {
            
           this.cbDoc.addItem(d.getDocName());
          
        }
        if(cbDoc.getSelectedItem()!=null){
       String seldoc= cbDoc.getSelectedItem().toString();
          
            did=getIdByNameDoctor(seldoc);
        }
        
        vid=getVidByPatient(pid);
       
//        ArrayList<Encounter> al=ds.getEncList();
//          for()
//   for(VitalSigns v:ds.getVitalList())
//        {
//            
//           //this.cbVitals.addItem(v.getDate());
//          
//        }
////if(cbVitals.getSelectedItem()!=null){
//       String selvit= cbVitals.getSelectedItem().toString();
//          
//            //vid=getIdByNameDoctor(selvit);
//            vid=getVidByPatient(pid);
//        }//      System.out.println(vid);
//      System.out.println(did);
//      txtVitalId.setText(String.valueOf(vid));
        
    }
    public String getIdByNamePatient(String selVal)
    {
        
        for(Patient p:ds.getPatient())
        {
            if(selVal.equals( p.getPatientName()))
            {
              pid=p.getPatientId();
            }
           
        }
        return pid;
        
    }
    public String getIdByNameDoctor(String selVal)
    {
        
        for(Doctor d:ds.getDoctr())
        {
            if(selVal.equals(d.getDocName()))
            {
              did=d.getDocID();
            }
           
        }
        return did;
        
    }
     
    public String getVidByPatient(String pid)
    {
        String vitalid="";
        System.out.println("getvidbyvid");
        for(VitalSigns v:ds.getVital())
        {
//             System.out.println(v.geti()+"getvidbyvid");

            if(pid.equals(v.getPatientId()))
            {
                System.out.println(v.getPatientId()+"getvidbypatient");

                    
              vitalid=v.getId();
            }
           
        }
        return vitalid;
        
    }

    
    
//    public String getIdByNamePatient(String name)
//    {
//        ArrayList<Patient> p=ds.getPatientList();
//        for(Patient pat:p)
//        {
//            if(p.))
//        }
//    }
   //String selVal=jcombo.getSelecteditem().toString();
    //jcombobox.addItem();
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnCreateEnc = new javax.swing.JButton();
        cbPatient = new javax.swing.JComboBox<>();
        cbDoc = new javax.swing.JComboBox<>();
        lblDate = new javax.swing.JLabel();
        txtDate = new javax.swing.JTextField();

        jLabel1.setText("Encounter");

        jLabel2.setText("Patients ");

        jLabel3.setText("Doctors");

        btnCreateEnc.setText("Create ");
        btnCreateEnc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateEncActionPerformed(evt);
            }
        });

        cbPatient.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "" }));
        cbPatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbPatientActionPerformed(evt);
            }
        });

        cbDoc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "" }));
        cbDoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbDocActionPerformed(evt);
            }
        });

        lblDate.setText("Date");

        txtDate.setText(" ");
        txtDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addGap(56, 56, 56))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addGap(62, 62, 62)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblDate)
                                .addGap(80, 80, 80)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbPatient, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbDoc, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtDate, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(156, 156, 156)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnCreateEnc)
                            .addComponent(jLabel1))))
                .addContainerGap(86, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDate)
                    .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cbPatient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cbDoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(btnCreateEnc)
                .addContainerGap(90, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    private void cbPatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbPatientActionPerformed
        // TODO add your handling code here:
        //int n=ds.getPatientList().size();
        
         
       
    }//GEN-LAST:event_cbPatientActionPerformed

    private void btnCreateEncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateEncActionPerformed
        // TODO add your handling code here:
       
        //ds.getEncList()
        
        String da=txtDate.getText().trim(); 
        Encounter enc=new Encounter(da,pid,did,vid);
        ds.addEncounter(enc);
        
    }//GEN-LAST:event_btnCreateEncActionPerformed

    private void cbDocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbDocActionPerformed
        // TODO add your handling code here:
//        int n=ds.getDoctorList().size();
//        for(int i=0;i<n;i++)
//        {
//            
//           cbDoc.addItem(ds.getDoctorList().get(i).getDocName());
//          
//        }
//         
//         String selVal= cbDoc.getSelectedItem().toString();
//          
//         //int n=ds.getPatientList().size();
//        //create function  getidbynmae
//        for(int i=0;i<n;i++)
//        {
//            if(selVal.equals( ds.getDoctorList().get(i).getDocName()))
//            {
//              did=ds.getDoctorList().get(i).getDocID();
//            }
//           
//        }
        
    }//GEN-LAST:event_cbDocActionPerformed

    private void txtDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDateActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreateEnc;
    private javax.swing.JComboBox<String> cbDoc;
    private javax.swing.JComboBox<String> cbPatient;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblDate;
    private javax.swing.JTextField txtDate;
    // End of variables declaration//GEN-END:variables
}
