/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import model.Community;
import model.DataService;
import model.Hospital;
/**
 *
 * @author madhav
 */
public class CreateHospJPanel extends javax.swing.JPanel {
    DataService hosp;
        String commId;
    /**
     * Creates new form CreateHospJPanel
     */
    ArrayList<Community> coms;
    public CreateHospJPanel(DataService hosp) {
        initComponents();
        this.hosp=hosp;
//        this.coms = this.hosp.getCommunity();
//        if(this.coms!=null) {
//            for(Community com: coms){
//            this.cbCommId.addItem(com.getCommunity());
//        }
//        

         hosp.createDummyComm();
         this.cbCommId.removeAllItems();
         for(Community cd:hosp.getCommunity())
         {
             this.cbCommId.addItem(cd.getCommunityID());
             
         }
         
         commId=(String)cbCommId.getSelectedItem();
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtHospId = new javax.swing.JTextField();
        txtHospName = new javax.swing.JTextField();
        txtCommId = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        lbCreateHosp = new javax.swing.JLabel();
        lbHospID = new javax.swing.JLabel();
        lbHospName = new javax.swing.JLabel();
        lbCommunityID2 = new javax.swing.JLabel();
        cbCommId = new javax.swing.JComboBox<>();
        lbCommunityID = new javax.swing.JLabel();

        txtHospId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHospIdActionPerformed(evt);
            }
        });

        btnSave.setText("Save Hospital Details");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        lbCreateHosp.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbCreateHosp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbCreateHosp.setText("Create Hospital Profile");

        lbHospID.setText("Hospital ID :");

        lbHospName.setText("Hospital Name :");

        lbCommunityID2.setText("Community ID :");

        cbCommId.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbCommId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbCommIdActionPerformed(evt);
            }
        });

        lbCommunityID.setText("Community ID :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbCreateHosp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbCommunityID2)
                            .addComponent(lbHospName)
                            .addComponent(lbHospID)
                            .addComponent(lbCommunityID))
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbCommId, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtHospId)
                            .addComponent(txtHospName)
                            .addComponent(txtCommId, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE))
                        .addGap(0, 48, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnSave)
                .addGap(102, 102, 102))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbCreateHosp)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbHospID)
                    .addComponent(txtHospId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbHospName)
                    .addComponent(txtHospName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbCommunityID2)
                    .addComponent(txtCommId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbCommId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbCommunityID))
                .addGap(18, 18, 18)
                .addComponent(btnSave)
                .addContainerGap(80, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtHospIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHospIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHospIdActionPerformed
    private String getCommunityByName(String name) {
        String cid="";
        if(this.coms!=null) {
            for(Community com: coms){
                if(com.getCommunityName().equals(name)) {
                    return com.getCommunityID();
                }
        }
        }
        return cid;
    }
    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
    String hospitalId = txtHospId.getText();
    if(hospitalId.isEmpty()){
            JOptionPane.showMessageDialog(this, "Hospital ID should not empty");
            return;
        }
    String hospitalName = txtHospName.getText();
    if(hospitalName.isEmpty()){
            JOptionPane.showMessageDialog(this, "Hospital Name should not empty");
            return;
        }
    String communityId = txtCommId.getText();
    String communityID = getCommunityByName((String)this.cbCommId.getSelectedItem());
    
    Hospital hp = hosp.addNewHosp();
    hp.setHospitalId(hospitalId);
    hp.setHospitalName(hospitalName);
    hp.setCommunityId(communityID);
    
    JOptionPane.showMessageDialog(this,"New Hospital Added to List");
    
    txtHospId.setText("");
    txtHospName.setText("");
    txtCommId.setText("");
    }//GEN-LAST:event_btnSaveActionPerformed

    private void cbCommIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbCommIdActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_cbCommIdActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox<String> cbCommId;
    private javax.swing.JLabel lbCommunityID;
    private javax.swing.JLabel lbCommunityID2;
    private javax.swing.JLabel lbCreateHosp;
    private javax.swing.JLabel lbHospID;
    private javax.swing.JLabel lbHospName;
    private javax.swing.JTextField txtCommId;
    private javax.swing.JTextField txtHospId;
    private javax.swing.JTextField txtHospName;
    // End of variables declaration//GEN-END:variables
}
