/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import model.DataService;
import model.Patient;

/**
 *
 * @author madhav
 */
public class FunctionPatientJPanel extends javax.swing.JPanel {

    /**
     * Creates new form FunctionPatientJPanel
     */
    DataService HAdmin;
    Patient p;
    public FunctionPatientJPanel(DataService HAdmin) {
        initComponents();
        this.HAdmin = HAdmin;
        this.p=p;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        splitFP = new javax.swing.JSplitPane();
        controlPanel = new javax.swing.JPanel();
        btnVD = new javax.swing.JButton();
        btnEPI = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        workAreaFP = new javax.swing.JPanel();

        btnVD.setText("View the Doctors");
        btnVD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVDActionPerformed(evt);
            }
        });

        btnEPI.setText("Encounter By Patient ID");
        btnEPI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEPIActionPerformed(evt);
            }
        });

        jButton1.setText("Create Patient");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("View/Update Patient");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout controlPanelLayout = new javax.swing.GroupLayout(controlPanel);
        controlPanel.setLayout(controlPanelLayout);
        controlPanelLayout.setHorizontalGroup(
            controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controlPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnVD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEPI, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        controlPanelLayout.setVerticalGroup(
            controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controlPanelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(btnEPI)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnVD)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addContainerGap(157, Short.MAX_VALUE))
        );

        splitFP.setLeftComponent(controlPanel);

        javax.swing.GroupLayout workAreaFPLayout = new javax.swing.GroupLayout(workAreaFP);
        workAreaFP.setLayout(workAreaFPLayout);
        workAreaFPLayout.setHorizontalGroup(
            workAreaFPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 283, Short.MAX_VALUE)
        );
        workAreaFPLayout.setVerticalGroup(
            workAreaFPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 288, Short.MAX_VALUE)
        );

        splitFP.setRightComponent(workAreaFP);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(splitFP)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(splitFP)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnVDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVDActionPerformed
        // TODO add your handling code here:
      ViewDocJPanel encounterPanel = new ViewDocJPanel(this.HAdmin);
      splitFP.setRightComponent(encounterPanel);
    }//GEN-LAST:event_btnVDActionPerformed

    private void btnEPIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEPIActionPerformed
        // TODO add your handling code here:
        ViewEncounterHistoryByPatientPanel encounterPanel = new ViewEncounterHistoryByPatientPanel(this.p,this.HAdmin);
        splitFP.setRightComponent(encounterPanel);
    }//GEN-LAST:event_btnEPIActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
                  CreatePatientJPanel encounterPanel = new CreatePatientJPanel(this.HAdmin);
                 splitFP.setRightComponent(encounterPanel); // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

               ViewPatientInfoJPanel encounterPanel = new ViewPatientInfoJPanel(this.HAdmin);
                 splitFP.setRightComponent(encounterPanel);

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEPI;
    private javax.swing.JButton btnVD;
    private javax.swing.JPanel controlPanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JSplitPane splitFP;
    private javax.swing.JPanel workAreaFP;
    // End of variables declaration//GEN-END:variables
}
