/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import model.CityList;
import model.DataService;

/**
 *
 * @author madhav
 */
public class FunctionCommunityAdmin extends javax.swing.JPanel {

    /**
     * Creates new form FunctionCommunityAdmin
     */
    
    DataService ciList;
    public FunctionCommunityAdmin(DataService ciList) {
        initComponents();
        this.ciList = ciList;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        lblCommManage = new javax.swing.JLabel();
        btnCommManage = new javax.swing.JButton();
        lblCityManage = new javax.swing.JLabel();
        btnCityManage = new javax.swing.JButton();
        lblHospManage = new javax.swing.JLabel();
        btnHospManage = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();

        lblCommManage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCommManage.setText("Community Management");

        btnCommManage.setText("Manage Communities");
        btnCommManage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCommManageActionPerformed(evt);
            }
        });

        lblCityManage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCityManage.setText("City Management");

        btnCityManage.setText("Manage Cities");
        btnCityManage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCityManageActionPerformed(evt);
            }
        });

        lblHospManage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHospManage.setText("Hospital Management");

        btnHospManage.setText("Manage Hospitals");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblHospManage, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btnCommManage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblCommManage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblCityManage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnCityManage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(btnHospManage, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 8, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(lblCommManage)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCommManage)
                .addGap(18, 18, 18)
                .addComponent(lblCityManage, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCityManage)
                .addGap(18, 18, 18)
                .addComponent(lblHospManage)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnHospManage)
                .addContainerGap(82, Short.MAX_VALUE))
        );

        jSplitPane1.setLeftComponent(jPanel1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 295, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 294, Short.MAX_VALUE)
        );

        jSplitPane1.setRightComponent(jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSplitPane1))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCommManageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCommManageActionPerformed
       
        CommunityJPanel cp = new CommunityJPanel(this.ciList);
        this.jSplitPane1.setRightComponent(cp);

        // TODO add your handling code here:
    }//GEN-LAST:event_btnCommManageActionPerformed

    private void btnCityManageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCityManageActionPerformed
         MainCityJPanel cityPanel = new MainCityJPanel(ciList);
       //CreateHospJPanel createPanel = new CreateHospJPanel();
        jSplitPane1.setRightComponent(cityPanel);


        // TODO add your handling code here:
    }//GEN-LAST:event_btnCityManageActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCityManage;
    private javax.swing.JButton btnCommManage;
    private javax.swing.JButton btnHospManage;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JLabel lblCityManage;
    private javax.swing.JLabel lblCommManage;
    private javax.swing.JLabel lblHospManage;
    // End of variables declaration//GEN-END:variables
}
