/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;
import ui.createVitalsJpanel;
import model.DataService;
//import ui.
/**
 *
 * @author madhav
 */
public class FunctionHospitalAdmin extends javax.swing.JPanel {

    /**
     * Creates new form FunctionHospitalAdmin
     */
    DataService HAdmin;
    public FunctionHospitalAdmin(DataService HAdmin) {
        initComponents();
         this.HAdmin = HAdmin;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        workAreaFHA = new javax.swing.JPanel();
        splitPaneFHA = new javax.swing.JSplitPane();
        controlPanelFHA = new javax.swing.JPanel();
        lbHAM = new javax.swing.JLabel();
        btnVSD = new javax.swing.JButton();
        lbVSM = new javax.swing.JLabel();
        btnHMA1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnVSD1 = new javax.swing.JButton();

        javax.swing.GroupLayout workAreaFHALayout = new javax.swing.GroupLayout(workAreaFHA);
        workAreaFHA.setLayout(workAreaFHALayout);
        workAreaFHALayout.setHorizontalGroup(
            workAreaFHALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 389, Short.MAX_VALUE)
        );
        workAreaFHALayout.setVerticalGroup(
            workAreaFHALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 342, Short.MAX_VALUE)
        );

        lbHAM.setText("Hospital Management ");

        btnVSD.setText("Manage Encounter Details Here");
        btnVSD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVSDActionPerformed(evt);
            }
        });

        lbVSM.setText("Vital Sign Management");

        btnHMA1.setText("Manage Hospital Details Here");
        btnHMA1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHMA1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Encounter Management");

        btnVSD1.setText("Manage Vital Sign Details Here");
        btnVSD1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVSD1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout controlPanelFHALayout = new javax.swing.GroupLayout(controlPanelFHA);
        controlPanelFHA.setLayout(controlPanelFHALayout);
        controlPanelFHALayout.setHorizontalGroup(
            controlPanelFHALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controlPanelFHALayout.createSequentialGroup()
                .addGroup(controlPanelFHALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(controlPanelFHALayout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(lbHAM))
                    .addGroup(controlPanelFHALayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jLabel2))
                    .addGroup(controlPanelFHALayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnHMA1))
                    .addGroup(controlPanelFHALayout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(lbVSM))
                    .addComponent(btnVSD1)
                    .addComponent(btnVSD))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        controlPanelFHALayout.setVerticalGroup(
            controlPanelFHALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controlPanelFHALayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbHAM)
                .addGap(18, 18, 18)
                .addComponent(btnHMA1)
                .addGap(18, 18, 18)
                .addComponent(lbVSM)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnVSD1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnVSD)
                .addContainerGap(156, Short.MAX_VALUE))
        );

        splitPaneFHA.setLeftComponent(controlPanelFHA);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(splitPaneFHA)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(splitPaneFHA, javax.swing.GroupLayout.Alignment.TRAILING)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnVSDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVSDActionPerformed
        // TODO add your handling code here:
        ViewEncounterHistoryJPanel encounterPanel = new ViewEncounterHistoryJPanel(this.HAdmin);
        splitPaneFHA.setRightComponent(encounterPanel);
    }//GEN-LAST:event_btnVSDActionPerformed

    private void btnVSD1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVSD1ActionPerformed
       createVitalsJpanel panel = new createVitalsJpanel(this.HAdmin);
       
//        CreateVitalsJpanel createVitalPanel = new CreateVitalsJpanel(HAdmin);
        splitPaneFHA.setRightComponent(panel);
             // TODO add your handling code here:
    }//GEN-LAST:event_btnVSD1ActionPerformed

    private void btnHMA1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHMA1ActionPerformed
        // TODO add your handling code here:
        MainHospJPanel mainPanel = new MainHospJPanel(HAdmin);
       //CreateHospJPanel createPanel = new CreateHospJPanel();
        splitPaneFHA.setRightComponent(mainPanel);
    }//GEN-LAST:event_btnHMA1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHMA1;
    private javax.swing.JButton btnVSD;
    private javax.swing.JButton btnVSD1;
    private javax.swing.JPanel controlPanelFHA;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lbHAM;
    private javax.swing.JLabel lbVSM;
    private javax.swing.JSplitPane splitPaneFHA;
    private javax.swing.JPanel workAreaFHA;
    // End of variables declaration//GEN-END:variables
}
