/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import model.DataService;
import model.Patient;

/**
 *
 * @author madhav
 */
public class FunctionPatientJPanel extends javax.swing.JPanel {

    /**
     * Creates new form FunctionPatientJPanel
     */
    DataService HAdmin;
    Patient p;
    public FunctionPatientJPanel(DataService HAdmin) {
        initComponents();
        this.HAdmin = HAdmin;
        this.p=p;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        splitFP = new javax.swing.JSplitPane();
        controlPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnVD = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnEPI = new javax.swing.JButton();
        workAreaFP = new javax.swing.JPanel();

        jLabel1.setText("Manage Encounter By Patient");

        btnVD.setText("View the Doctors");
        btnVD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVDActionPerformed(evt);
            }
        });

        jLabel2.setText("View the Doctor");

        btnEPI.setText("Encounter By Patient ID");
        btnEPI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEPIActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout controlPanelLayout = new javax.swing.GroupLayout(controlPanel);
        controlPanel.setLayout(controlPanelLayout);
        controlPanelLayout.setHorizontalGroup(
            controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controlPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnVD, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1)
                        .addGroup(controlPanelLayout.createSequentialGroup()
                            .addGap(35, 35, 35)
                            .addComponent(jLabel2))))
                .addContainerGap(35, Short.MAX_VALUE))
            .addGroup(controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(controlPanelLayout.createSequentialGroup()
                    .addGap(16, 16, 16)
                    .addComponent(btnEPI)
                    .addContainerGap(26, Short.MAX_VALUE)))
        );
        controlPanelLayout.setVerticalGroup(
            controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controlPanelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addGap(67, 67, 67)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnVD)
                .addContainerGap(133, Short.MAX_VALUE))
            .addGroup(controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(controlPanelLayout.createSequentialGroup()
                    .addGap(52, 52, 52)
                    .addComponent(btnEPI)
                    .addContainerGap(214, Short.MAX_VALUE)))
        );

        splitFP.setLeftComponent(controlPanel);

        javax.swing.GroupLayout workAreaFPLayout = new javax.swing.GroupLayout(workAreaFP);
        workAreaFP.setLayout(workAreaFPLayout);
        workAreaFPLayout.setHorizontalGroup(
            workAreaFPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 283, Short.MAX_VALUE)
        );
        workAreaFPLayout.setVerticalGroup(
            workAreaFPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 288, Short.MAX_VALUE)
        );

        splitFP.setRightComponent(workAreaFP);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(splitFP)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(splitFP)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnVDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVDActionPerformed
        // TODO add your handling code here:
      ViewDocJPanel encounterPanel = new ViewDocJPanel(this.HAdmin);
      splitFP.setRightComponent(encounterPanel);
    }//GEN-LAST:event_btnVDActionPerformed

    private void btnEPIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEPIActionPerformed
        // TODO add your handling code here:
        ViewEncounterHistoryByPatientPanel encounterPanel = new ViewEncounterHistoryByPatientPanel(this.p,this.HAdmin);
        splitFP.setRightComponent(encounterPanel);
    }//GEN-LAST:event_btnEPIActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEPI;
    private javax.swing.JButton btnVD;
    private javax.swing.JPanel controlPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSplitPane splitFP;
    private javax.swing.JPanel workAreaFP;
    // End of variables declaration//GEN-END:variables
}
