/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;
import model.DataService;
/**
 *
 * @author madhav
 */
public class MainHospAdminJPanel extends javax.swing.JPanel {

    /**
     * Creates new form MainHospAdminJPanel
     */
    DataService HAdmin;
    public MainHospAdminJPanel(DataService HAdmin) {
        initComponents();
        this.HAdmin = HAdmin;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        controlPanelHA = new javax.swing.JPanel();
        btnCreateHA = new javax.swing.JButton();
        btnViewHA = new javax.swing.JButton();
        btnUpdateHA = new javax.swing.JButton();
        workAreaHA = new javax.swing.JPanel();

        btnCreateHA.setText("Create");
        btnCreateHA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateHAActionPerformed(evt);
            }
        });

        btnViewHA.setText("View / Delete");
        btnViewHA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewHAActionPerformed(evt);
            }
        });

        btnUpdateHA.setText("Update");
        btnUpdateHA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateHAActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout controlPanelHALayout = new javax.swing.GroupLayout(controlPanelHA);
        controlPanelHA.setLayout(controlPanelHALayout);
        controlPanelHALayout.setHorizontalGroup(
            controlPanelHALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controlPanelHALayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(controlPanelHALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnUpdateHA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(controlPanelHALayout.createSequentialGroup()
                        .addGroup(controlPanelHALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnViewHA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnCreateHA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        controlPanelHALayout.setVerticalGroup(
            controlPanelHALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controlPanelHALayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(btnCreateHA)
                .addGap(18, 18, 18)
                .addComponent(btnViewHA)
                .addGap(18, 18, 18)
                .addComponent(btnUpdateHA)
                .addContainerGap(160, Short.MAX_VALUE))
        );

        jSplitPane1.setLeftComponent(controlPanelHA);

        javax.swing.GroupLayout workAreaHALayout = new javax.swing.GroupLayout(workAreaHA);
        workAreaHA.setLayout(workAreaHALayout);
        workAreaHALayout.setHorizontalGroup(
            workAreaHALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 283, Short.MAX_VALUE)
        );
        workAreaHALayout.setVerticalGroup(
            workAreaHALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 288, Short.MAX_VALUE)
        );

        jSplitPane1.setRightComponent(workAreaHA);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSplitPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSplitPane1)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreateHAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateHAActionPerformed
        // TODO add your handling code here:
        CreateHospAdminJPanel createPanel = new CreateHospAdminJPanel(HAdmin);
       
        jSplitPane1.setRightComponent(createPanel);
        
    }//GEN-LAST:event_btnCreateHAActionPerformed

    private void btnViewHAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewHAActionPerformed
        // TODO add your handling code here:
        ViewHospAdminJPanel viewPanel = new ViewHospAdminJPanel(HAdmin);
       
        jSplitPane1.setRightComponent(viewPanel);
    }//GEN-LAST:event_btnViewHAActionPerformed

    private void btnUpdateHAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateHAActionPerformed
        // TODO add your handling code here:
        UpdateHospAdminJPanel updatePanel = new UpdateHospAdminJPanel(HAdmin);
       
        jSplitPane1.setRightComponent(updatePanel);
    }//GEN-LAST:event_btnUpdateHAActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreateHA;
    private javax.swing.JButton btnUpdateHA;
    private javax.swing.JButton btnViewHA;
    private javax.swing.JPanel controlPanelHA;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JPanel workAreaHA;
    // End of variables declaration//GEN-END:variables
}
