/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import model.DataService;

/**
 *
 * @author madhav
 */
public class SysAdminJPanel extends javax.swing.JPanel {

    /**
     * Creates new form SysAdminJPanel
     */
    public SysAdminJPanel(DataService d) {
        initComponents();
        this.d=d;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    DataService d;
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        sysAdMngmtPanel = new javax.swing.JPanel();
        lblSysAMg = new javax.swing.JLabel();
        lblDocMg = new javax.swing.JLabel();
        btnSysAMg = new javax.swing.JButton();
        btnDocMg = new javax.swing.JButton();
        lblPatientMg = new javax.swing.JLabel();
        btnPatientMg = new javax.swing.JButton();
        lblHospAMg = new javax.swing.JLabel();
        btnHospAMg = new javax.swing.JButton();
        btnCommAMg = new javax.swing.JButton();
        lblCommAMg = new javax.swing.JLabel();
        lblHospMg = new javax.swing.JLabel();
        btnHospMg = new javax.swing.JButton();
        lblCommMg = new javax.swing.JLabel();
        btnCommMg = new javax.swing.JButton();
        lblEncMg = new javax.swing.JLabel();
        btnEncMg = new javax.swing.JButton();
        lblVitMg = new javax.swing.JLabel();
        btnVitMg = new javax.swing.JButton();
        btnEncMg1 = new javax.swing.JButton();
        sysAdOpsPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();

        lblSysAMg.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        lblSysAMg.setText("System Admin Management");

        lblDocMg.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        lblDocMg.setText("Doctor Management");

        btnSysAMg.setText("Manage System Admin Details");
        btnSysAMg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSysAMgActionPerformed(evt);
            }
        });

        btnDocMg.setText("Manage Doctor Details");
        btnDocMg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDocMgActionPerformed(evt);
            }
        });

        lblPatientMg.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        lblPatientMg.setText("Patient Management");

        btnPatientMg.setText("Manage Patient Details");
        btnPatientMg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPatientMgActionPerformed(evt);
            }
        });

        lblHospAMg.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        lblHospAMg.setText("Hospital Admin Management");

        btnHospAMg.setText("Manage Hospital Admin Details");
        btnHospAMg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHospAMgActionPerformed(evt);
            }
        });

        btnCommAMg.setText("Manage Community Admin Details");
        btnCommAMg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCommAMgActionPerformed(evt);
            }
        });

        lblCommAMg.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        lblCommAMg.setText("Community Admin Management");

        lblHospMg.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        lblHospMg.setText("Hospital Management");

        btnHospMg.setText("Manage Hospital Details");
        btnHospMg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHospMgActionPerformed(evt);
            }
        });

        lblCommMg.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        lblCommMg.setText("Community Management");

        btnCommMg.setText("Manage Community Details");
        btnCommMg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCommMgActionPerformed(evt);
            }
        });

        lblEncMg.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        lblEncMg.setText("Encounter Management");

        btnEncMg.setText("Manage Encounter Details");
        btnEncMg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEncMgActionPerformed(evt);
            }
        });

        lblVitMg.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        lblVitMg.setText("Vital Signs Management");

        btnVitMg.setText("Manage Vital Signs Details");
        btnVitMg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVitMgActionPerformed(evt);
            }
        });

        btnEncMg1.setText("Manage Encounter Details");
        btnEncMg1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEncMg1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout sysAdOpsPanelLayout = new javax.swing.GroupLayout(sysAdOpsPanel);
        sysAdOpsPanel.setLayout(sysAdOpsPanelLayout);
        sysAdOpsPanelLayout.setHorizontalGroup(
            sysAdOpsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sysAdOpsPanelLayout.createSequentialGroup()
                .addGap(111, 111, 111)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(492, Short.MAX_VALUE))
        );
        sysAdOpsPanelLayout.setVerticalGroup(
            sysAdOpsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sysAdOpsPanelLayout.createSequentialGroup()
                .addContainerGap(444, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(237, 237, 237))
        );

        javax.swing.GroupLayout sysAdMngmtPanelLayout = new javax.swing.GroupLayout(sysAdMngmtPanel);
        sysAdMngmtPanel.setLayout(sysAdMngmtPanelLayout);
        sysAdMngmtPanelLayout.setHorizontalGroup(
            sysAdMngmtPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sysAdMngmtPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(sysAdMngmtPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblHospAMg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDocMg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblDocMg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnPatientMg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblPatientMg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblSysAMg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSysAMg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblCommAMg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnHospAMg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCommAMg, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(lblHospMg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnHospMg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblCommMg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCommMg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblEncMg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEncMg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblVitMg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnVitMg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sysAdOpsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEncMg1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        sysAdMngmtPanelLayout.setVerticalGroup(
            sysAdMngmtPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sysAdMngmtPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblSysAMg, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(sysAdMngmtPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(sysAdMngmtPanelLayout.createSequentialGroup()
                        .addComponent(btnSysAMg, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblPatientMg, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnPatientMg)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblDocMg, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnDocMg)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblHospAMg, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnHospAMg)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblCommAMg, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCommAMg)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblHospMg, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnHospMg)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblCommMg, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCommMg)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblEncMg, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(sysAdMngmtPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnEncMg)
                            .addComponent(btnEncMg1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblVitMg, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnVitMg))
                    .addComponent(sysAdOpsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jSplitPane1.setLeftComponent(sysAdMngmtPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSysAMgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSysAMgActionPerformed
        // TODO add your handling code here:
        MainSysAdminJPanel panel = new MainSysAdminJPanel(d);
        this.jSplitPane1.setRightComponent(panel);
    }//GEN-LAST:event_btnSysAMgActionPerformed

    private void btnDocMgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDocMgActionPerformed
        // TODO add your handling code here:
        FunctionDoctorJPanel panel = new FunctionDoctorJPanel(this.d);
        this.jSplitPane1.setRightComponent(panel);
    }//GEN-LAST:event_btnDocMgActionPerformed

    private void btnPatientMgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPatientMgActionPerformed
        // TODO add your handling code here:
         FunctionPatientJPanel panel = new FunctionPatientJPanel(this.d);
        this.jSplitPane1.setRightComponent(panel);
    }//GEN-LAST:event_btnPatientMgActionPerformed

    private void btnHospAMgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHospAMgActionPerformed
        // TODO add your handling code here:
        MainHospJPanel panel = new MainHospJPanel(this.d);
        this.jSplitPane1.setRightComponent(panel);
    }//GEN-LAST:event_btnHospAMgActionPerformed

    private void btnCommAMgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCommAMgActionPerformed
        // TODO add your handling code here:
        FunctionCommunityAdmin panel = new FunctionCommunityAdmin(this.d);
        this.jSplitPane1.setRightComponent(panel);
    }//GEN-LAST:event_btnCommAMgActionPerformed

    private void btnHospMgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHospMgActionPerformed
        // TODO add your handling code here:
        MainHospJPanel panel = new MainHospJPanel(this.d);
        this.jSplitPane1.setRightComponent(panel);
    }//GEN-LAST:event_btnHospMgActionPerformed

    private void btnCommMgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCommMgActionPerformed
        // TODO add your handling code here:
        CommunityJPanel panel = new CommunityJPanel(this.d);
        this.jSplitPane1.setRightComponent(panel);
    }//GEN-LAST:event_btnCommMgActionPerformed

    private void btnEncMgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEncMgActionPerformed
        // TODO add your handling code here:
        CreateEncounterJPanel panel = new CreateEncounterJPanel(this.d);
        this.jSplitPane1.setRightComponent(panel);
    }//GEN-LAST:event_btnEncMgActionPerformed

    private void btnVitMgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVitMgActionPerformed
        // TODO add your handling code here:
        viewVitalsJpanel panel = new viewVitalsJpanel(this.d);
        this.jSplitPane1.setRightComponent(panel);
    }//GEN-LAST:event_btnVitMgActionPerformed

    private void btnEncMg1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEncMg1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEncMg1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCommAMg;
    private javax.swing.JButton btnCommMg;
    private javax.swing.JButton btnDocMg;
    private javax.swing.JButton btnEncMg;
    private javax.swing.JButton btnEncMg1;
    private javax.swing.JButton btnHospAMg;
    private javax.swing.JButton btnHospMg;
    private javax.swing.JButton btnPatientMg;
    private javax.swing.JButton btnSysAMg;
    private javax.swing.JButton btnVitMg;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JLabel lblCommAMg;
    private javax.swing.JLabel lblCommMg;
    private javax.swing.JLabel lblDocMg;
    private javax.swing.JLabel lblEncMg;
    private javax.swing.JLabel lblHospAMg;
    private javax.swing.JLabel lblHospMg;
    private javax.swing.JLabel lblPatientMg;
    private javax.swing.JLabel lblSysAMg;
    private javax.swing.JLabel lblVitMg;
    private javax.swing.JPanel sysAdMngmtPanel;
    private javax.swing.JPanel sysAdOpsPanel;
    // End of variables declaration//GEN-END:variables
}
