/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.DataService;
import model.SystemAdmin;

/**
 *
 * @author madhav
 */
public class UpdateSysAJPanel extends javax.swing.JPanel {

    /**
     * Creates new form UpdateSysAJPanel
     */
    DataService sAdmin;
    public UpdateSysAJPanel(DataService sAdmin) {
        initComponents();
        this.sAdmin = sAdmin;
        populateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblViewSysA = new javax.swing.JLabel();
        txtSysAName = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSysA = new javax.swing.JTable();
        txtSysAUname = new javax.swing.JTextField();
        txtSysAPswd = new javax.swing.JTextField();
        lblSysAID = new javax.swing.JLabel();
        lblSysAName = new javax.swing.JLabel();
        lblSysAuname = new javax.swing.JLabel();
        lblSysApswd = new javax.swing.JLabel();
        txtSysAID = new javax.swing.JTextField();
        btnUpdSysA = new javax.swing.JButton();

        lblViewSysA.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        lblViewSysA.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblViewSysA.setText("View System Administrator Details");

        tblSysA.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Username", "Password"
            }
        ));
        tblSysA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSysAMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblSysA);

        txtSysAUname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSysAUnameActionPerformed(evt);
            }
        });

        txtSysAPswd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSysAPswdActionPerformed(evt);
            }
        });

        lblSysAID.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblSysAID.setText("ID:");

        lblSysAName.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblSysAName.setText("Name:");

        lblSysAuname.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblSysAuname.setText("Username:");

        lblSysApswd.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblSysApswd.setText("Password:");

        txtSysAID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSysAIDActionPerformed(evt);
            }
        });

        btnUpdSysA.setText("Update");
        btnUpdSysA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdSysAActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(358, 358, 358)
                .addComponent(btnUpdSysA)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(248, 248, 248)
                                .addComponent(lblViewSysA, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(289, 289, 289)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblSysAuname, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblSysApswd, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblSysAName)
                                    .addComponent(lblSysAID, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(38, 38, 38)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtSysAPswd, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                                    .addComponent(txtSysAUname)
                                    .addComponent(txtSysAName)
                                    .addComponent(txtSysAID))))
                        .addGap(0, 275, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(lblViewSysA, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSysAID)
                    .addComponent(txtSysAID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSysAName)
                    .addComponent(txtSysAName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSysAuname)
                    .addComponent(txtSysAUname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSysApswd)
                    .addComponent(txtSysAPswd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addComponent(btnUpdSysA)
                .addGap(31, 31, 31))
        );
    }// </editor-fold>//GEN-END:initComponents
    public boolean isEmpty(String c){
        return c != null && c.length() ==0;
    }
    private void txtSysAUnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSysAUnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSysAUnameActionPerformed

    private void txtSysAPswdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSysAPswdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSysAPswdActionPerformed

    private void txtSysAIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSysAIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSysAIDActionPerformed

    private void btnUpdSysAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdSysAActionPerformed
        // TODO add your handling code here:
        
        if(sAdmin!=null){
            DefaultTableModel model= (DefaultTableModel) tblSysA.getModel();
            if(tblSysA.getSelectedRowCount() == 1){            
                if(isEmpty(txtSysAID.getText())) {
                JOptionPane.showMessageDialog(this, "Please enter System Admin ID");
                return;
                }
                String sysId = txtSysAID.getText();
                if(isEmpty(txtSysAName.getText())) {
                JOptionPane.showMessageDialog(this, "Please enter System Admin Name");
                return;
                }
                String sysN = txtSysAName.getText();
                if(isEmpty(txtSysAUname.getText())) {
                    JOptionPane.showMessageDialog(this, "Please enter System Admin Username");
                    return;
                }
                String sysUname = txtSysAUname.getText();
                if(isEmpty(txtSysAPswd.getText())) {
                    JOptionPane.showMessageDialog(this, "Please enter System Admin Password");
                    return;
                }
                String sysPswd = txtSysAPswd.getText();
                int selectedRowIndex = tblSysA.getSelectedRow();
        
            SystemAdmin sysA = sAdmin.getSAdmin().get(selectedRowIndex);
            sysA.setSysID(sysId);
            sysA.setSysName(sysN);
            sysA.setSysUsername(sysUname);
            sysA.setSysPassword(sysPswd);
            }
        
        JOptionPane.showMessageDialog(this, "The record has been updated successfully");
        populateTable();
        }
        
        else{
            JOptionPane.showMessageDialog(this,"Row empty.");
        }
    }//GEN-LAST:event_btnUpdSysAActionPerformed

    private void tblSysAMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSysAMouseClicked
        // TODO add your handling code here:
        int selectedRowIndex = tblSysA.getSelectedRow();
            if(selectedRowIndex<0){
                JOptionPane.showMessageDialog(this, "Please select a System Admin profile to Update");
                return;
            }
            DefaultTableModel model= (DefaultTableModel) tblSysA.getModel();
            SystemAdmin selectedSysAdmin = (SystemAdmin) model.getValueAt(selectedRowIndex, 0);
            txtSysAID.setText(String.valueOf(selectedSysAdmin.getSysID()));
            txtSysAName.setText(String.valueOf(selectedSysAdmin.getSysName()));
            txtSysAUname.setText(String.valueOf(selectedSysAdmin.getSysUsername()));
            txtSysAPswd.setText(String.valueOf(selectedSysAdmin.getSysPassword()));
    }//GEN-LAST:event_tblSysAMouseClicked
    
                                       
    
    private void populateTable() {
        DefaultTableModel model= (DefaultTableModel) tblSysA.getModel();
        model.setRowCount(0);
        
        for(SystemAdmin sa : sAdmin.getSAdmin()){
            Object[] row = new Object[4];
            row[0] = sa;
            row[1] = sa.getSysName();
            row[2] = sa.getSysUsername();
            row[3] = sa.getSysPassword();
            model.addRow(row);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnUpdSysA;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblSysAID;
    private javax.swing.JLabel lblSysAName;
    private javax.swing.JLabel lblSysApswd;
    private javax.swing.JLabel lblSysAuname;
    private javax.swing.JLabel lblViewSysA;
    private javax.swing.JTable tblSysA;
    private javax.swing.JTextField txtSysAID;
    private javax.swing.JTextField txtSysAName;
    private javax.swing.JTextField txtSysAPswd;
    private javax.swing.JTextField txtSysAUname;
    // End of variables declaration//GEN-END:variables
}
