/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.DataService;
import model.HospitalAdmin;

/**
 *
 * @author madhav
 */
public class UpdateHospAdminJPanel extends javax.swing.JPanel {

    /**
     * Creates new form UpdateHospAdminJPanel
     */
    DataService HAdmin;
    public UpdateHospAdminJPanel(DataService HAdmin) {
        initComponents();
        this.HAdmin = HAdmin;
        populateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbHospName = new javax.swing.JLabel();
        lbCommunityID = new javax.swing.JLabel();
        txtHospAdminId = new javax.swing.JTextField();
        txtHospAdminName = new javax.swing.JTextField();
        txtHospAdminUsername = new javax.swing.JTextField();
        lbHospID = new javax.swing.JLabel();
        lbUpdateAdminHospital = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblHospAdmin = new javax.swing.JTable();
        btnUpdateHospAdmin = new javax.swing.JButton();
        lbCommunityID1 = new javax.swing.JLabel();
        txtHospAdminPass = new javax.swing.JTextField();

        lbHospName.setText("Hospital Admin Name :");

        lbCommunityID.setText("Hospital Admin Username :");

        txtHospAdminId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHospAdminIdActionPerformed(evt);
            }
        });

        lbHospID.setText("Hospital Admin ID :");

        lbUpdateAdminHospital.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbUpdateAdminHospital.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbUpdateAdminHospital.setText("Update Hospital Admin Details");

        tblHospAdmin.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "HA ID", "HA Name", "HA Username", "HA Password"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblHospAdmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblHospAdminMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblHospAdmin);

        btnUpdateHospAdmin.setText("Update");
        btnUpdateHospAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateHospAdminActionPerformed(evt);
            }
        });

        lbCommunityID1.setText("Hospital Admin Password:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbUpdateAdminHospital, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbHospID, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbCommunityID1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbCommunityID, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbHospName, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtHospAdminPass, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdateHospAdmin)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txtHospAdminId, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtHospAdminName, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtHospAdminUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(95, 95, 95))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lbUpdateAdminHospital)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbHospID)
                    .addComponent(txtHospAdminId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtHospAdminName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbHospName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbCommunityID)
                    .addComponent(txtHospAdminUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbCommunityID1)
                    .addComponent(txtHospAdminPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addComponent(btnUpdateHospAdmin)
                .addContainerGap(11, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtHospAdminIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHospAdminIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHospAdminIdActionPerformed
public boolean isEmpty(String c){
        return c != null && c.length() ==0;
        }
public boolean isStrongPassword(String s) {  
    return s != null && s.matches("^(?=.[a-z])(?=.[A-Z])(?=.\\d)(?=.[@$!%?&])[A-Za-z\\d@$!%?&]{8,}$");  
    }
    private void tblHospAdminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblHospAdminMouseClicked
        // TODO add your handling code here:
        int selectedRowIndex = tblHospAdmin.getSelectedRow();
        if(selectedRowIndex<0){
            JOptionPane.showMessageDialog(this, "Please select an employee profile to Update");
            return;
        }
          
        
        DefaultTableModel model= (DefaultTableModel) tblHospAdmin.getModel();
        HospitalAdmin selectedHospitalAdmin = (HospitalAdmin) model.getValueAt(selectedRowIndex, 0);
        txtHospAdminId.setText(String.valueOf(selectedHospitalAdmin.gethAdminId()));
        txtHospAdminName.setText(selectedHospitalAdmin.gethAdminName());
        txtHospAdminUsername.setText(selectedHospitalAdmin.gethAdminUserName());
        txtHospAdminPass.setText(selectedHospitalAdmin.gethAdminPassword());
    }//GEN-LAST:event_tblHospAdminMouseClicked

    private void btnUpdateHospAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateHospAdminActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model= (DefaultTableModel) tblHospAdmin.getModel();
        if(tblHospAdmin.getSelectedRowCount() == 1){
            String haid=txtHospAdminId.getText();
            if(isEmpty(txtHospAdminId.getText())) {
            JOptionPane.showMessageDialog(this, "Please enter admin ID");
            return;
        }
            String hosapName=txtHospAdminName.getText();
            if(isEmpty(txtHospAdminName.getText())) {
            JOptionPane.showMessageDialog(this, "Please enter admin name");
            return;
        }
            String hospaUser=txtHospAdminUsername.getText();
            if(isEmpty(txtHospAdminUsername.getText())) {
            JOptionPane.showMessageDialog(this, "Please enter admin username");
            return;
        }
            String hospaPass=txtHospAdminPass.getText();
            if(!isStrongPassword(txtHospAdminPass.getText())) {
            JOptionPane.showMessageDialog(this, "Please enter a Strong Password");
            return;
        }
            int selectedRowIndex = tblHospAdmin.getSelectedRow();

            HospitalAdmin hp = HAdmin.getHospAdmin().get(selectedRowIndex);

            hp.sethAdminId(haid);
            hp.sethAdminName(hosapName);
            hp.sethAdminUserName(hospaUser);
            hp.sethAdminPassword(hospaPass);
        }

        JOptionPane.showMessageDialog(this, "The record has been updated successfully");
        populateTable();
    }//GEN-LAST:event_btnUpdateHospAdminActionPerformed
    private void populateTable() {
        DefaultTableModel model= (DefaultTableModel) tblHospAdmin.getModel();
        model.setRowCount(0);
        
        for(HospitalAdmin ha : HAdmin.getHospAdmin()){
            Object[] row = new Object[4];
            row[0] = ha;
            row[1] = ha.gethAdminName();
            row[2] = ha.gethAdminUserName();
            row[3] = ha.gethAdminPassword();
            model.addRow(row);
            
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnUpdateHospAdmin;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbCommunityID;
    private javax.swing.JLabel lbCommunityID1;
    private javax.swing.JLabel lbHospID;
    private javax.swing.JLabel lbHospName;
    private javax.swing.JLabel lbUpdateAdminHospital;
    private javax.swing.JTable tblHospAdmin;
    private javax.swing.JTextField txtHospAdminId;
    private javax.swing.JTextField txtHospAdminName;
    private javax.swing.JTextField txtHospAdminPass;
    private javax.swing.JTextField txtHospAdminUsername;
    // End of variables declaration//GEN-END:variables
}
