/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import assignment.pkg2.Database;
import assignment.pkg2.Patient;
import assignment.pkg2.VitalSigns;
import javax.swing.JOptionPane;

/**
 *
 * @author pavanmadhavnainala
 */
public class updateVitalsJpanel extends javax.swing.JPanel {

    /**
     * Creates new form updateVitalsJpanel
     */
    
    Database vital;
    VitalSigns vs;
    
    public updateVitalsJpanel(Database vital) {
        initComponents();
        
        
        
        this.vital = vital;
        
    }
    
    
    VitalSigns searchPatient(String id) {
        for(VitalSigns vs:this.vital.getVital()) {
            if(vs.getPatientId().matches(id)) {
                return vs;
            }
            
        }
        return null;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    public boolean isNumeric(String s) {  
    return s != null && s.matches("[-+]?\\d*\\.?\\d+");  
    } 
    
    
            
    public boolean isDouble(String d) {  
    return d != null && d.matches("^[0-9]\\d*(\\.\\d+)?$");  
    }        
    
    public boolean isEmpty(String c){
        
        return c != null && c.length() ==0;
        
    }
    
    
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        lblRR = new javax.swing.JLabel();
        txtAge = new javax.swing.JTextField();
        txtBodyTemp = new javax.swing.JTextField();
        txtPulse = new javax.swing.JTextField();
        txtBP = new javax.swing.JTextField();
        txtRR = new javax.swing.JTextField();
        btnUpdate = new javax.swing.JButton();
        lblDate = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        lblPatientId = new javax.swing.JLabel();
        lblAge = new javax.swing.JLabel();
        lblBodyTemp = new javax.swing.JLabel();
        lblPulse = new javax.swing.JLabel();
        lblBP = new javax.swing.JLabel();
        cbPatient = new javax.swing.JComboBox<>();

        lblTitle.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Update Vitals Signs");

        btnSearch.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        btnSearch.setText("Search Patient ID");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        lblRR.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        lblRR.setText("  Respiration Rate:");

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        lblDate.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        lblDate.setText("          Date : ");

        jDateChooser1.setForeground(new java.awt.Color(51, 51, 51));

        lblPatientId.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        lblPatientId.setText("             Patient ID :");

        lblAge.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        lblAge.setText("                     Age  :");

        lblBodyTemp.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        lblBodyTemp.setText("Body Temperature :");

        lblPulse.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        lblPulse.setText("                   Pulse :");

        lblBP.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        lblBP.setText("     Blood Pressure :");

        cbPatient.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 914, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cbPatient, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSearch)
                .addGap(17, 17, 17))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(265, 265, 265)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(127, 127, 127)
                            .addComponent(btnUpdate))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblPatientId)
                                    .addComponent(lblAge, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblPulse)
                                    .addComponent(lblBP)
                                    .addComponent(lblRR)
                                    .addComponent(lblBodyTemp, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(42, 42, 42)
                                    .addComponent(lblDate)))
                            .addGap(30, 30, 30)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtAge)
                                .addComponent(txtBodyTemp)
                                .addComponent(txtPulse)
                                .addComponent(txtBP)
                                .addComponent(jDateChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                                .addComponent(txtRR))))
                    .addContainerGap(352, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(lblTitle)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSearch)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(cbPatient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(353, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(105, 105, 105)
                    .addComponent(lblPatientId)
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblAge)
                        .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblBodyTemp)
                        .addComponent(txtBodyTemp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblPulse)
                        .addComponent(txtPulse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblBP)
                        .addComponent(txtBP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblRR)
                        .addComponent(txtRR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblDate)
                        .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(49, 49, 49)
                    .addComponent(btnUpdate)
                    .addContainerGap(39, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed

        String fPatient = txtSearch.getText();
        
        this.vs = this.searchPatient(fPatient);
        if(vs==null) {
            JOptionPane.showMessageDialog(this, "Patient ID doesn't exist. Please enter valid Patient Id.");
            return;
        }
        
        txtBodyTemp.setText(String.valueOf(vs.getBodyTemperature()));
        txtAge.setText(String.valueOf(vs.getAge()));
        txtPulse.setText(String.valueOf(vs.getPulse()));
        txtBP.setText(String.valueOf(vs.getBloodPressure()));
        txtRR.setText(String.valueOf(vs.getRespirationRate()));
        cbPatient.setSelectedItem(vs.getPatientId());
        
        
        
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
            
        
        
            vital.createDummyPatient();
            this.cbPatient.removeAllItems();
            for(Patient p:vital.getPatient())
            {
            this.cbPatient.addItem(p.getPatientId());
            
            }
          
            String patientId= (String)cbPatient.getSelectedItem(); 
            
            String bodyTemp=txtBodyTemp.getText();
            String age=txtAge.getText();
            String pulse= txtPulse.getText();
            String bloodPressure=txtBP.getText();
            String respirationRate=txtRR.getText();
            
            
            
        
            vs.setAge(Integer.parseInt(age));
        
        
        
        
        vs.setPatientId(patientId);
        vs.setBodyTemperature(Double.parseDouble(bodyTemp));
        vs.setBloodPressure(Double.parseDouble(bloodPressure));
        vs.setPulse(Integer.parseInt(pulse));
        vs.setRespirationRate(Integer.parseInt(respirationRate));
        
        
        
        
        JOptionPane.showMessageDialog(this, "Employee Profile Modified");


        // TODO add your handling code here:
    }//GEN-LAST:event_btnUpdateActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> cbPatient;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel lblAge;
    private javax.swing.JLabel lblBP;
    private javax.swing.JLabel lblBodyTemp;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblPatientId;
    private javax.swing.JLabel lblPulse;
    private javax.swing.JLabel lblRR;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtBP;
    private javax.swing.JTextField txtBodyTemp;
    private javax.swing.JTextField txtPulse;
    private javax.swing.JTextField txtRR;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
